version: "3.7"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017-27019:27017-27019
  rabbitmq:
    image: rabbitmq:3.7
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    entrypoint: "/bin/bash -c 'rabbitmq-plugins enable rabbitmq_management && docker-entrypoint.sh rabbitmq-server'"
